### ISSUE TITLE
Start application error

### ISSUE THREAD

**Issue by jaonoctus** [MiguelMedeiros/mr-watson#2]
## Expected Behavior
I hoped to run your brilliant project but I did not succeed.

## Actual Behavior
```fish
yarn run v1.6.0
$ node ./bin/www
/mr-watson/node_modules/fingerprintjs2/dist/fingerprint2.min.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t,r){"use strict";"function"==typeof window.define&&window.define.amd?window.define(r):"undefined"!=typeof module&&module.exports?module.exports=r():t.exports?t.exports=r():t.Fingerprint2=r()}(0,this,function(){"use strict";var e=function(t){if(!(this instanceof e))return new e(t);this.options=this.extend(t,{swfContainerId:"fingerprintjs2",swfPath:"flash/compiled/FontList.swf",detectScreenOrientation:!0,sortPluginsFor:[/palemoon/i],userDefinedFonts:[],excludeDoNotTrack:!0,excludePixelRatio:!0}),this.nativeForEach=Array.prototype.forEach,this.nativeMap=Array.prototype.map};return e.prototype={extend:function(e,t){if(null==e)return t;for(var r in e)null!=e[r]&&t[r]!==e[r]&&(t[r]=e[r]);return t},get:function(e){var t=this,r={data:[],addPreprocessedComponent:function(e){var n=e.value;"function"==typeof t.options.preprocessor&&(n=t.options.preprocessor(e.

ReferenceError: window is not defined
    at t.options.extend.swfContainerId (/mr-watson/node_modules/fingerprintjs2/dist/fingerprint2.min.js:1:93)
    at Object.<anonymous> (/mr-watson/node_modules/fingerprintjs2/dist/fingerprint2.min.js:1:267)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mr-watson/node_modules/blinktrade/lib/wsTransport.js:13:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Steps to Reproduce the Problem

  1. `yarn` (or `npm install`) to install dependencies.
  2. `yarn start` (or `npm start`) to start the application.

## Specifications

  - Version: source from master (a5abc694f7a78e290c8d086d62512222a8a57dc0)
  - Platform: GNU/Linux
  - Subsystem: Ubuntu 17.10

**Comment by tiagosh** [comment]
I just had the very same issue while trying to dockerize mr watson and found that the blinktrade api code is failing to detect it's running under node (and not the browser). But after I ran "npm install" again it fixed it. Still not sure what's going on.

This line is returning false to this.isNode: https://github.com/blinktrade/BlinkTradeJS/blob/master/src/wsTransport.js#L153

And this is where isNode is defined: https://github.com/blinktrade/BlinkTradeJS/blob/master/src/base.js#L58

**Comment by tiagosh** [comment]
@jaonoctus if you just want to try Mr Watson and happen to have docker installed, I just sent this following PR that will run the code in a container and then you shouldn't hit this specific bug: https://github.com/MiguelMedeiros/mr-watson/pull/3

**Comment by MiguelMedeiros** [comment]
Hey @jaonoctus!
The last release of the npm package "blinktrade" has already fixed this issue.
You can see the fix here: 
https://github.com/blinktrade/BlinkTradeJS/commit/03568f33f5c67facf05e314ee2a149ae611db3c0

I've already updated the package.json to get the last version of it.
Can you try to install again? Thanks!
